channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - tensorflow-gpu
  - keras-gpu
  - scikit-learn
  - pandas
  - biopython
  - h5py
  - matplotlib-base
  - snakemake-minimal
  - htslib=1.18
  - bedtools=2.31.0