channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - tensorflow-gpu
  - keras-gpu
  - scikit-learn
  - pandas
  - matplotlib-base
  - snakemake-minimal
  - h5py
  - biopython
  - htslib