channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.78
  - htslib=1.18
  - h5py=3.9.0
  - tensorflow=2.12.0
  - keras=2.12.0
  - scikit-learn=1.3.0
  - pandas=2.1.1
  - snakemake-minimal=7.32.4
  - matplotlib-base=3.7.2
  - bedtools=2.31.0
  - wget=1.20.3
  - pip

