channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.81=py312h98912ed_1
  - pybedtools
  - h5py
  - keras
  - scikit-learn
  - numpy
  - pandas
  - matplotlib-base

