channels:
  - letaylor
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - pandas=1.1.4
  - scipy=1.5.3
  - numpy=1.19.4
  - scanpy=1.6.0
  - plotnine=0.7.1
  - r-optparse=1.6.6
  - r-dirichletreg=0.7_0
  - r-cowplot=1.1.1
  - r-reshape2=1.4.4
  - r-tidyverse=1.3.0
  - r-data.table=1.13.6
