channels:
  - letaylor
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - pandas=1.1.4
  - scipy=1.5.3
  - numpy=1.19.4
  - scanpy=1.6.0
  - plotnine=0.7.1
  - seaborn=0.11.1
  - r-optparse=1.6.6
  - r-tidyverse=1.3.0
  - r-scales=1.0.0
  - r-ggrepel=0.9.1
  - r-matrix=1.2_17
  - bioconductor-biocparallel=1.24.0
  - bioconductor-deseq2=1.30.0
  - bioconductor-glmgampoi=1.2.0
  - bioconductor-edger=3.32.0
  - bioconductor-limma=3.46.0
  - bioconductor-mast=1.16.0
  - bioconductor-ihw=1.18.0
  - bioconductor-fgsea=1.16.0
