channels:
  - conda-forge
  - r
  - bioconda
  - defaults
  - letaylor
dependencies:
  - pip
  - plotnine
  - seaborn>=0.11.2
  - statsmodels>=0.13.2
  - matplotlib-base
  - scanpy
  - pandas
  - scipy
  - htslib>=1.15.1
