channels:
  - conda-forge
  - r
  - bioconda
  - defaults
  - letaylor
dependencies:
  - pip
  - plotnine=0.12.4
  - seaborn>=0.11.2
  - statsmodels>=0.13.2
  - matplotlib-base=3.8.2
  - scanpy=1.9.6
  - pandas=2.1.4
  - scipy=1.11.4
  - htslib>=1.15.1
