channels:
  - letaylor
  - conda-forge
  - r
  - bioconda
  - defaults
dependencies:
  - pip
  - plotnine
  - seaborn>=0.11.2
  - statsmodels>=0.13.2
  - scanpy=1.5.2.dev0
  - pandas=1.4.2
  - scipy=1.8.1
  - htslib>=1.15.1
