channels:
  - letaylor
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pandas
  - numpy
  - scipy
  - tables
  - scanpy
  - python-igraph
  - plotnine
  - kneed
  - louvain
  - leidenalg
  - pyro-ppl
  - torch
  - matplotlib
  - loompy
  - ipython
  - psutil
  - pip
  - pip:
     - git+https://github.com/broadinstitute/CellBender.git
