channels:
  - letaylor
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python-igraph
  - plotnine
  - kneed
  - louvain
  - leidenalg
  - pip
  - anndata
  - scanpy
  - pandas
  - numpy
  - scipy
  - matplotlib
  - ipython
  - jupyter
  - jupyter_contrib_nbextensions
  - notebook<7.0.0
  - nbconvert<7.0.0
  - lxml_html_clean
