channels:
  - letaylor
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python-igraph
  - plotnine
  - kneed
  - louvain
  - leidenalg
  - pip
  - anndata
  - scanpy
  - pandas
  - numpy
  - scipy
  - matplotlib
